name: build-staging (Android)

env:
  AAB_PATH: android/app/build/outputs/bundle/release/app-release.aab

on:
  workflow_dispatch:
  pull_request:
    types:
      - closed

jobs:
  run-checks:
    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event.pull_request.merged == true && github.base_ref == vars.RELEASE_BRANCH && startsWith(github.head_ref, 'release/'))

    uses: ./.github/workflows/pull-request-checks.yml

  build-android:
    needs: run-checks
    runs-on: ubuntu-latest
    timeout-minutes: 30
    defaults:
      run:
        shell: bash
        working-directory: ./android

    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: install dependencies
        run: yarn install

      - name: decode keystore
        run: echo ${{ secrets.ANDROID_UPLOAD_KEY_BASE64 }} | base64 -d > app/upload.jks

      - name: make gradlew executable
        run: chmod +x ./gradlew

      - name: build AAB
        run: ./gradlew bundleRelease
        env:
          NUBBLE_STORE_PASSWORD: ${{ secrets.ANDROID_STORE_PASSWORD }}
          NUBBLE_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          NUBBLE_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}

      - name: decode google-service-account.json
        run: echo ${{ secrets.ANDROID_SERVICE_ACCOUNT_BASE64 }} | base64 -d > google-service-account.json

      - name: upload AAB to play store
        run: fastlane upload_internal

      - name: upload AAB to artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release.aab
          path: ${{ env.AAB_PATH }}
          retention-days: 7
