name: bump-version

on:
  push:
    tags:
      - '**'

jobs:
  bump-version:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ vars.RELEASE_BRANCH }}

      - name: make bump-version.sh executable
        run: chmod +x scripts/bump-version.sh

      - name: run bump-version.sh
        run: ./scripts/bump-version.sh $GITHUB_REF_NAME
