name: create-release-changelog

on:
  pull_request:
    types:
      - closed

permissions:
  contents: write

jobs:
  create-release:
    if: ${{ github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release/') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install conventional-changelog
        run: npm install -g conventional-changelog-cli

      - name: Generate Changelog
        run: |
          TAG_NAME=$(echo "${{ github.event.pull_request.head.ref }}" | sed 's/release\///')
          echo "TAG_NAME: $TAG_NAME"


          PREVIOUS_TAG=$(git describe --tags `git rev-list --tags --max-count=1` || echo "none")
          if [ "$PREVIOUS_TAG" == "none" ]; then
            echo "No previous tag found, generating changelog from scratch"
            conventional-changelog -p angular -r 0 -o CHANGELOG.md -s -k package.json --commit-path . --infile CHANGELOG.md
          else
            echo "Generating changelog from $PREVIOUS_TAG to $TAG_NAME"
            conventional-changelog -p angular -r 0 -o CHANGELOG.md -s -k package.json --commit-path . --infile CHANGELOG.md --tag-prefix=v --from $PREVIOUS_TAG --to $TAG_NAME
          fi

      - name: Create GitHub Release
        run: |
          gh release create "v${TAG_NAME}" --title "Release v${TAG_NAME}" --notes-file CHANGELOG.md
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
