name: create-release-changelog

on:
  workflow_dispatch:

jobs:
  create-release-changelog:
    name: create-release-changelog
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: install dependencies
        run: yarn install

      - name: get current and previous tag
        id: tags
        run: |
          current_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          previous_tag=$(git describe --tags `git rev-list --tags --skip=1 --max-count=1`)
          echo "Current Tag: $current_tag"
          echo "Previous Tag: $previous_tag"

          echo "current_tag=$current_tag" >> $GITHUB_ENV
          echo "previous_tag=$previous_tag" >> $GITHUB_ENV

      - name: create empty changelog if not exists
        run: |
          if [ ! -f CHANGELOG.md ]; then
            echo "# Changelog" > CHANGELOG.md
          fi

      - name: generate changelog
        id: changelog
        run: |
          yarn global add conventional-changelog-cli
          conventional-changelog -p angular -i CHANGELOG.md -s --commit-path .
          cat CHANGELOG.md

      - name: create release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.current_tag }}
          name: ${{ env.current_tag }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
